spring.datasource.url=jdbc:mysql://presend-guard.ce9i0aak21eg.us-east-1.rds.amazonaws.com:3306/Presend_Guard?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=UTF-8
spring.datasource.username=bitty2003
spring.datasource.password=Jcy030822!!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration